---

- name: "CoreDNS integrated with Route53 - POC"
  hosts: bind_servers
  become: true

  environment:
    http_proxy: http://10.11.100.201:3128
    https_proxy: http://10.11.100.201:3128
  
  vars:
    coredns_base_path: "/home/coredns"
    ansible_become_password: "{{ lookup('amazon.aws.aws_secret', 'ANSIBLE_BECOME_PASSWORD', region='us-west-2') }}"
    aws_secret_arns_file_path: ../terraform/aws_secret_arns.yml

    coredns_access: arn:aws:secretsmanager:us-west-2:406663345920:secret:service-coredns-AWS_ACCESS_KEY_ID-JJvEZZ
    coredns_secret: arn:aws:secretsmanager:us-west-2:406663345920:secret:service-coredns-AWS_SECRET_ACCESS_KEY-QfC9ey

    zones:
      - zonename: library.ucsb.edu
        hosted_zone_id: "Z02600803IA0I0TCHM0GV"
        zone_refresh: "5m"
      - zonename: alexandria.ucsb.edu
        hosted_zone_id: "Z0698383335PF0QE6QOR1"
        zone_refresh: "5m"
      - zonename: 87.111.128.in-addr.arpa
        hosted_zone_id: "Z01908603CS9OAOT0VQV8"
        zone_refresh: "5m"


  tasks:

    - name: "checking for {{ aws_secret_arns_file_path }}"
      ansible.builtin.stat:
        path: "{{ aws_secret_arns_file_path }}"
      register: arns_stat

    - name: "Include terraform generated AWS SecretsManager ARNs"
      include_vars: "{{ aws_secret_arns_file_path }}"
      when: arns_stat.stat.exists

    - name: "Results of stat'ing {{ aws_secret_arns_file_path }}"
      debug:
        msg: "{{ arns_stat }}"

    - ansible.builtin.set_fact:
        aws_access_key_id: "{{ lookup('amazon.aws.aws_secret', 'service-coredns-AWS_ACCESS_KEY_ID', region='us-west-2') }}"
        aws_secret_access_key: "{{ lookup('amazon.aws.aws_secret', 'service-coredns-AWS_SECRET_ACCESS_KEY', region='us-west-2') }}"

      tags: 
        - role:coredns:install
        - role:coredns:install:secrets
        - role:coredns:tss
      delegate_to: 127.0.0.1

    - name: debug aws keys
      debug:
        msg: "aws_access_key_id: {{aws_access_key_id}}"

    - name: debug aws secret keys
      debug:
        msg: "aws_secret_access_key: {{aws_secret_access_key}}"


    - name: create container directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: 0775
        owner: root
        recurse: yes
      tags: 
        - role:coredns:install
        - role:coredns:install:paths
      loop: 
        - "{{ coredns_base_path }}/config"
        - "{{ coredns_base_path }}/data"
      
    - name: create config file
      ansible.builtin.template:
        src: templates/Corefile.j2
        dest: "{{ coredns_base_path }}/config/Corefile"
      tags: 
        - role:coredns:install
        - role:coredns:install:corefile
        - role:coredns:config

    - name: disable systemd-resolved
      ansible.builtin.service:
        name: systemd-resolved
        state: stopped
        enabled: false
      tags: 
        - role:coredns:install
        - role:coredns:install:resolved
    
    - name: restart docker to ensure iptables integration
      ansible.builtin.service:
        name: docker
        state: restarted
      tags: 
        - role:coredns:install
        - role:coredns:install:docker
        - never  
    
    - name: create container
      community.docker.docker_container:
        name: coredns
        recreate: yes
        restart: yes
        state: started
        image: coredns/coredns
        command: -conf /root/Corefile
        ports:
          - "53:53/tcp"
          - "53:53/udp"
        volumes:
          - "{{ coredns_base_path }}/config:/root:rw"
        env:
            AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
            AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
      tags: 
        - role:coredns:install
        - role:coredns:install:container
