

name: "terraform: initialize, plan and deploy - route53 / coredns integration"
on:
  push:
    branches:
      - 'main'
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-*.yml'
    
jobs:

  init:
    name: "terraform: setup, initialize, plan, and deploy"
    runs-on: ubuntu-latest 
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: checkout branch
        uses: actions/checkout@v3

      - name: "terraform: installing"
        uses: hashicorp/setup-terraform@v2

      - name: "terraform: init"
        run: cd terraform; terraform init -upgrade
    
      - name: "terraform: plan stage"
        id: plan
        run: cd terraform; terraform plan -no-color
      
      - name: "terraform: apply"
        id: apply
        run: cd terraform; terraform apply -auto-approve
      